#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("uhacapp.Resource", IsApplication=true)]

namespace uhacapp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int apply = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int buttonlayout = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int pay = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int paybank = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ttloan = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int view = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050011
			public const int Text = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int Text1 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int Text2 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int Text3 = 2131034132;
			
			// aapt resource value: 0x7f05000f
			public const int btnBackLoan = 2131034127;
			
			// aapt resource value: 0x7f05001f
			public const int btnBackNewMember = 2131034143;
			
			// aapt resource value: 0x7f050006
			public const int btnLoan = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int btnLoans = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int btnNew = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int btnPayment = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int btnPaymentBills = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int btnSave = 2131034116;
			
			// aapt resource value: 0x7f050020
			public const int btnSaveNewMember = 2131034144;
			
			// aapt resource value: 0x7f050015
			public const int fragment_container = 2131034133;
			
			// aapt resource value: 0x7f050022
			public const int imageView1 = 2131034146;
			
			// aapt resource value: 0x7f050002
			public const int txtAccountNo = 2131034114;
			
			// aapt resource value: 0x7f05001e
			public const int txtAd = 2131034142;
			
			// aapt resource value: 0x7f050003
			public const int txtAmount = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int txtBills = 2131034113;
			
			// aapt resource value: 0x7f05001d
			public const int txtCN = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int txtCS = 2131034140;
			
			// aapt resource value: 0x7f05000b
			public const int txtCol = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int txtComAddress = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int txtComContact = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int txtComaker = 2131034124;
			
			// aapt resource value: 0x7f05001a
			public const int txtDOB = 2131034138;
			
			// aapt resource value: 0x7f050018
			public const int txtFN = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int txtLN = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int txtMN = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int txtSex = 2131034139;
			
			// aapt resource value: 0x7f05000a
			public const int txtla = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int txtlll = 2131034112;
			
			// aapt resource value: 0x7f050016
			public const int txtllnm = 2131034134;
			
			// aapt resource value: 0x7f050021
			public const int txtllp = 2131034145;
			
			// aapt resource value: 0x7f050010
			public const int txtm = 2131034128;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BillsPay = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Loan = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LoanList = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Loanlist_row = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Member = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Member_row = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int NewMember = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Payment = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Splash = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
